"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, CheckCheck, GitCompareArrows, Network, Radar, Users, Workflow, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ErrorNotice, PageTitle } from "@/components/common";
import { useProfiles } from "@/lib/use-profiles";
import { request } from "@/lib/api";
import { dimensions } from "@/lib/types";
import { initials } from "@/lib/utils";

export default function Dashboard() {
  const { profiles, error } = useProfiles();
  const [health, setHealth] = useState<{ status: string; database: string } | null>(null);
  useEffect(() => { request<{status: string; database: string}>("/health").then(setHealth).catch(() => setHealth({ status: "offline", database: "unavailable" })); }, []);
  return <><PageTitle eyebrow="CONNECTIONS WITH PURPOSE" title="Great work starts with the right people." description="Discover professional affinity. Uncover complementary strengths. Build something together." action={<Button asChild variant="outline"><Link href="/engine"><Workflow size={16} /> How it works <ArrowUpRight size={16} /></Link></Button>} />
    <ErrorNotice message={error} />
    <section className="hero-panel"><div className="hero-copy"><div className="hero-kicker"><span className="status-dot" /> INTRODUCING THE HYBRID DECISION ENGINE</div><h2>More than a match.<br /><span>A meaningful connection.</span></h2><p>Your next collaborator might think like you.<br />Or bring exactly what you’re missing. Discover both.</p><div className="hero-actions"><Button asChild><Link href="/match">Create a match <ArrowRight size={17} /></Link></Button><Link className="text-link" href="/ranking">Explore professional ranking <ArrowUpRight size={15} /></Link></div><div className="hero-footnote"><CheckCheck size={14} /> Transparent scores <span>·</span> Local semantic intelligence <span>·</span> No API key needed</div></div><div className="network-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="network-line line-one" /><div className="network-line line-two" /><div className="network-line line-three" /><div className="network-center"><Network size={39} /></div><span className="network-node node-one">AI<span>AI & data</span></span><span className="network-node node-two">PM<span>Product</span></span><span className="network-node node-three">UX<span>Design</span></span><span className="network-node node-four">ENG<span>Engineering</span></span><span className="network-spark spark-one" /><span className="network-spark spark-two" /></div></section>
    <div className="stats-grid"><div className="stat-card"><span><Users size={17} /> Demo professionals</span><strong>{profiles.length || "—"}<small>across {new Set(profiles.map(p => p.role).filter(Boolean)).size || "—"} professional roles</small></strong></div><div className="stat-card"><span><Workflow size={17} /> Matching dimensions</span><strong>06<small>one explainable decision</small></strong></div><div className="stat-card"><span><Zap size={17} /> Engine architecture</span><strong>Hybrid<small>structured + semantic + complementary</small></strong></div><div className="stat-card"><span><CheckCheck size={17} /> Database status</span><strong className="status-value">{health ? (health.database === "connected" ? "Connected" : "Unavailable") : "Checking…"}<small>{health?.database === "connected" ? "PostgreSQL + pgvector" : "Inline demo matching available with backend"}</small></strong></div></div>
    <div className="section-heading"><h2>Make your next connection</h2><span className="small-text muted">Two ways to find professional synergy</span></div>
    <div className="two-columns mode-cards"><Link href="/match" className="panel mode-card"><span className="mode-icon"><GitCompareArrows size={23} /></span><span className="mini-badge">1 : 1</span><h3>Compare two professionals</h3><p>Understand the connection between two people, from shared skills to complementary expertise.</p><span className="mode-link">Analyze a match <ArrowRight size={17} /></span></Link><Link href="/ranking" className="panel mode-card"><span className="mode-icon blue"><Radar size={23} /></span><span className="mini-badge">1 : N</span><h3>Find the strongest connections</h3><p>Explore an entire professional network and surface the most promising people to collaborate with.</p><span className="mode-link">Explore rankings <ArrowRight size={17} /></span></Link></div>
    <div className="dashboard-bottom"><section className="panel formula-preview"><div className="panel-heading"><h2>Every score has a reason.</h2><Link href="/engine" aria-label="Explore score formula"><ArrowUpRight size={19} /></Link></div><p className="muted small-text">Six weighted dimensions power every comparison.</p><div className="formula-strip">{dimensions.map(d => <span key={d.key} style={{ width: `${d.weight}%`, background: d.color }} />)}</div><div className="formula-legend">{dimensions.map(d => <div key={d.key}><i style={{ background: d.color }} /><span>{d.label}</span><strong>{d.weight}%</strong></div>)}</div><div className="formula-note"><CheckCheck size={15} /> Scores calculated by our engine. Explanations grounded in evidence.</div></section><section className="panel people-preview"><div className="panel-heading"><h2>Meet the network</h2><Link className="text-link" href="/profiles">View all <ArrowUpRight size={14} /></Link></div>{profiles.slice(3, 7).map(p => <div className="person-row" key={p.user_id}><span className="avatar small">{initials(p.name)}</span><div><strong>{p.name}</strong><span>{p.role}</span></div><span className="muted small-text">{p.experience_years} yrs</span></div>)}{!profiles.length && <p className="muted small-text">Connect the backend to explore the demo network.</p>}</section></div>
  </>;
}
