import { BrainCircuit, CheckCheck, Fingerprint, GitMerge, Scale } from "lucide-react";
import { PageTitle } from "@/components/common";
import { dimensions } from "@/lib/types";
import { EngineFlow } from "@/components/engine-flow";

export default function EnginePage() {
  return <><PageTitle eyebrow="BUILT TO BE UNDERSTOOD" title="No black box. Just better connections." description="Meet THDE-1.0: the Twintro Hybrid Decision Engine. Every dimension is visible. Every score is explainable." />
    <section className="engine-intro panel"><div><span className="eyebrow">THE PRINCIPLE</span><h2>Similarity finds common ground.<br /><span className="accent">Complementarity reveals possibility.</span></h2><p>A great collaborator can share your expertise or bring a professionally useful strength you don’t have. Our engine measures both.</p></div><Fingerprint size={100} strokeWidth={1} /></section>
    <div className="section-heading"><h2>From profiles to possibility</h2><span className="small-text muted">Evidence → decision → explanation</span></div><EngineFlow />
    <section className="panel weights-panel"><div className="panel-heading"><div><span className="eyebrow">THE DECISION FORMULA</span><h2>Six dimensions. 100% transparent.</h2></div><span className="mini-badge">THDE-1.0</span></div><div className="weights-grid">{dimensions.map(d => <div key={d.key}><span style={{ color: d.color }}>{d.weight}<small>%</small></span><h3>{d.label}</h3><div className="bar-track"><div style={{ width: `${d.weight * 3}%`, background: d.color }} /></div></div>)}</div><code className="formula-code">Affinity = Σ (available score × weight) / Σ available weights</code><p className="small-text muted">Every component is scored from 0 to 100. API affinity is rounded to one decimal place.</p></section>
    <div className="two-columns"><section className="panel explanation-card"><h3><BrainCircuit size={20} /> Concept-level semantic matching</h3><p>Skills and interests combine 40% normalized exact overlap with 60% semantic similarity. We compare each concept against the other profile’s concepts, then average the best matches in both directions.</p><div className="concept-example"><span>Machine learning</span><span>↔</span><span>Artificial intelligence</span></div><p>Roles combine 70% semantic similarity and 30% family similarity. Industry uses exact matches, configured relationships, then semantic fallback.</p></section><section className="panel explanation-card"><h3><GitMerge size={20} /> Useful differences, measured</h3><p>Complementarity combines 70% role relationships and 30% skill domain relationships. Matrices are symmetric and configurable. Being different alone does not imply a strong collaboration.</p><div className="concept-example"><span>Engineering</span><span>+</span><span>Product strategy</span></div><p>Experience compares junior, mid, senior, lead, and expert bands. Even the largest band difference receives 25/100.</p></section></div>
    <div className="two-columns"><section className="panel explanation-card"><h3><CheckCheck size={20} /> Affinity is not confidence</h3><p>Affinity measures compatibility in the available evidence. Confidence measures profile completeness and the availability of matching dimensions, from 0 to 1.</p><p>Missing interests are excluded from the affinity formula, with their weight redistributed. Less information lowers confidence. An empty comparison is explicitly marked as insufficient evidence.</p></section><section className="panel explanation-card"><h3><Scale size={20} /> Ranking that scales</h3><p>Up to 10,000 candidates receive a full engine evaluation. Larger stored pools combine 200 pgvector semantic candidates with 100 complementary candidates, then deduplicate and fully score that union.</p><p>Ranking is ordered by affinity, then confidence and user ID for stable ties. Explanations are generated only for the top requested results.</p></section></div>
    <div className="match-levels panel"><h3>Reading your match</h3>{[["90–100", "Exceptional"], ["80–89.9", "Strong"], ["70–79.9", "Good"], ["60–69.9", "Moderate"], ["40–59.9", "Low"], ["0–39.9", "Weak"]].map(([range, label]) => <div key={label}><strong>{range}%</strong><span>{label} Match</span></div>)}</div>
  </>;
}
